const IMG = {
  //charicatureGraphics ---------------------------------------------

  AstronautIceCream: ("../resources/graphics/charicatureGraphics/Astronaut Ice Cream.png"),
  BarberSkater: ("../resources/graphics/charicatureGraphics/Barber Skater.png"),
  BasketBallBombers: ("../resources/graphics/charicatureGraphics/Basketball Bombers.png"),
  Bomber: ("../resources/graphics/charicatureGraphics/Bomber.png"),
  BoomboxRobot: ("../resources/graphics/charicatureGraphics/Boombox Robot.png"),
  BoxingChampion: ("../resources/graphics/charicatureGraphics/Boxing Champion.png"),
  BrickGamers: ("../resources/graphics/charicatureGraphics/Brick Gamers.png"),
  BrooklynBaseball: ("../resources/graphics/charicatureGraphics/Brooklyn Baseball.png"),
  BurgerBastard: ("../resources/graphics/charicatureGraphics/Burger Bastard.png"),
  BurgerScooter: ("../resources/graphics/charicatureGraphics/Burger Scooter.png"),
  CaferacerHelmet: ("../resources/graphics/charicatureGraphics/Caferacer Helmet.png"),
  CashRules: ("../resources/graphics/charicatureGraphics/Cash Rules.png"),
  ChainsawKiller: ("../resources/graphics/charicatureGraphics/Chainsaw KIller.png"),
  ChocolateSquad: ("../resources/graphics/charicatureGraphics/Chocolate Squad.png"),
  CigaretteKiller: ("../resources/graphics/charicatureGraphics/Cigarette Killer.png"),
  ClassicCameraman: ("../resources/graphics/charicatureGraphics/Classic Cameraman.png"),
  Diver: ("../resources/graphics/charicatureGraphics/Diver.png"),
  DonutSkater: ("../resources/graphics/charicatureGraphics/Donut Skater.png"),
  DoubleStickMan: ("../resources/graphics/charicatureGraphics/Double Stick Man.png"),
  Fighter: ("../resources/graphics/charicatureGraphics/Fighter.png"),
  FootballKing: ("../resources/graphics/charicatureGraphics/Football King.png"),
  FootballPlayer: ("../resources/graphics/charicatureGraphics/Football Player.png"),
  FrankRace: ("../resources/graphics/charicatureGraphics/Frank Race.png"),
  GameKid: ("../resources/graphics/charicatureGraphics/Game Kid.png"),
  GameMachine: ("../resources/graphics/charicatureGraphics/Game Machine.png"),
  GameOn1: ("../resources/graphics/charicatureGraphics/Game On 1.png"),
  GameOn2: ("../resources/graphics/charicatureGraphics/Game On 2.png"),
  GamersKiller: ("../resources/graphics/charicatureGraphics/Gamers Killer.png"),
  GiftFromOuterSpace: ("../resources/graphics/charicatureGraphics/Gift From Outer Space.png"),
  Golfer: ("../resources/graphics/charicatureGraphics/Golfer.png"),
  GramophoneHead: ("../resources/graphics/charicatureGraphics/Gramophone Head.png"),
  GrenadeBrain: ("../resources/graphics/charicatureGraphics/Grenade Brain.png"),
  GrenadeHeart: ("../resources/graphics/charicatureGraphics/Grenade Heart.png"),
  GrenadeRibcage: ("../resources/graphics/charicatureGraphics/Grenade Ribcage.png"),
  Grenade: ("../resources/graphics/charicatureGraphics/Grenade.png"),
  HeartToKill: ("../resources/graphics/charicatureGraphics/Heart To Kill.png"),
  Hello: ("../resources/graphics/charicatureGraphics/Hello.png"),
  ILikeDonut: ("../resources/graphics/charicatureGraphics/I Like Donut.png"),
  ILoveBurger: ("../resources/graphics/charicatureGraphics/I Love Burger.png"),
  IceCreamNinja: ("../resources/graphics/charicatureGraphics/Ice Cream Ninja.png"),
  IceCreamTruck: ("../resources/graphics/charicatureGraphics/Ice Cream Truck.png"),
  KillerMinibike: ("../resources/graphics/charicatureGraphics/Killer Minibike.png"),
  KillerSkater: ("../resources/graphics/charicatureGraphics/Killer Skater.png"),
  LetsPaint: ("../resources/graphics/charicatureGraphics/Let's Paint.png"),
  LetsPlay: ("../resources/graphics/charicatureGraphics/Let's Play.png"),
  LetsPlay2: ("../resources/graphics/charicatureGraphics/Let's Play 2.png"),
  LightBoy: ("../resources/graphics/charicatureGraphics/Light Boy.png"),
  MicrophoneKing: ("../resources/graphics/charicatureGraphics/Microphone King.png"),
  MoneyTakers: ("../resources/graphics/charicatureGraphics/Money Takers.png"),
  Money: ("../resources/graphics/charicatureGraphics/Money.png"),
  MrCoffee: ("../resources/graphics/charicatureGraphics/Mr Coffee.png"),
  MummyRace: ("../resources/graphics/charicatureGraphics/Mummy Race.png"),
  PeaceChar: ("../resources/graphics/charicatureGraphics/Peace.png"),
  Pilot: ("../resources/graphics/charicatureGraphics/Pilot.png"),
  PizzaBeard: ("../resources/graphics/charicatureGraphics/Pizza Beard.png"),
  PizzaGangster: ("../resources/graphics/charicatureGraphics/Pizza Gangster.png"),
  PizzaSkater: ("../resources/graphics/charicatureGraphics/Pizza Skater.png"),
  PlayerHead1: ("../resources/graphics/charicatureGraphics/Player Head 1.png"),
  PlayerHead2: ("../resources/graphics/charicatureGraphics/Player Head 2.png"),
  PlayerSkater: ("../resources/graphics/charicatureGraphics/Player Skater.png"),
  Polaroid: ("../resources/graphics/charicatureGraphics/Polaroid.png"),
  Racer: ("../resources/graphics/charicatureGraphics/Racer.png"),
  RamenStyle: ("../resources/graphics/charicatureGraphics/Ramen Style.png"),
  RobotBoombox: ("../resources/graphics/charicatureGraphics/Robot Boombox.png"),
  RubixKiller: ("../resources/graphics/charicatureGraphics/Rubix Killer.png"),
  Sailor: ("../resources/graphics/charicatureGraphics/Sailor.png"),
  SamuraiRider: ("../resources/graphics/charicatureGraphics/Samurai Rider.png"),
  Samurai: ("../resources/graphics/charicatureGraphics/Samurai.png"),
  Savage: ("../resources/graphics/charicatureGraphics/Savage.png"),
  ScooterSkater: ("../resources/graphics/charicatureGraphics/Scooter Skater.png"),
  Shooter: ("../resources/graphics/charicatureGraphics/Shooter.png"),
  SkateBastard: ("../resources/graphics/charicatureGraphics/Skate Bastard.png"),
  SkaterBomb: ("../resources/graphics/charicatureGraphics/Skater Bomb.png"),
  Skatespace: ("../resources/graphics/charicatureGraphics/Skatespace.png"),
  Soldier: ("../resources/graphics/charicatureGraphics/Soldier.png"),
  SpaceBike: ("../resources/graphics/charicatureGraphics/Space Bike.png"),
  SpaceJump: ("../resources/graphics/charicatureGraphics/Space Jump.png"),
  SpaceRacer: ("../resources/graphics/charicatureGraphics/Space Racer.png"),
  SpaceSlider: ("../resources/graphics/charicatureGraphics/Space Slider.png"),
  StayFresh: ("../resources/graphics/charicatureGraphics/Stay Fresh.png"),
  SteampunkHeart: ("../resources/graphics/charicatureGraphics/Steampunk Heart.png"),
  SteampunkOwl: ("../resources/graphics/charicatureGraphics/Steampunk Owl.png"),
  SteampunkRibcage: ("../resources/graphics/charicatureGraphics/Steampunk Ribcage.png"),
  SteampunkTRex: ("../resources/graphics/charicatureGraphics/Steampunk T Rex.png"),
  StreetBasketball: ("../resources/graphics/charicatureGraphics/Street Basketball.png"),
  StreetBeetle: ("../resources/graphics/charicatureGraphics/Street Beetle.png"),
  StreetBomber: ("../resources/graphics/charicatureGraphics/Street Bomber.png"),
  StreetGamers: ("../resources/graphics/charicatureGraphics/Street Gamers.png"),
  StreetKing: ("../resources/graphics/charicatureGraphics/Street King.png"),
  StreetSoccer: ("../resources/graphics/charicatureGraphics/Street Soccer.png"),
  Surprise: ("../resources/graphics/charicatureGraphics/Surprise.png"),
  Taco: ("../resources/graphics/charicatureGraphics/Taco.png"),
  ToasterMonster: ("../resources/graphics/charicatureGraphics/Toaster Monster.png"),
  TrainKiller: ("../resources/graphics/charicatureGraphics/Train Killer.png"),
  Vandalism: ("../resources/graphics/charicatureGraphics/Vandalism.png"),
  Viking: ("../resources/graphics/charicatureGraphics/Viking.png"),
  VintageRobot: ("../resources/graphics/charicatureGraphics/Vintage Robot.png"),
  WarTank: ("../resources/graphics/charicatureGraphics/War Tank.png"),
  YourTimeWillCome: ("../resources/graphics/charicatureGraphics/Your Time Will Come.png"),
  ZombieCassette: ("../resources/graphics/charicatureGraphics/Zombie Cassette.png"),

  //pocketGraphics ---------------------------------------------

  Abduction: ("../resources/graphics/pocketGraphics/alien abduction pocketSource.png"),
  AngryWaves: ("../resources/graphics/pocketGraphics/Angry waves pocket.png"),
  Aquarium: ("../resources/graphics/pocketGraphics/aquarium pocket.png"),
  BeAwesome: ("../resources/graphics/pocketGraphics/be awesome pocketSource.png"),
  Cactus: ("../resources/graphics/pocketGraphics/cactus pocket.png"),
  CatSkeleton: ("../resources/graphics/pocketGraphics/cat skeleton pocketSource.png"),
  ChildMoon: ("../resources/graphics/pocketGraphics/Child on moon pocket.png"),
  CourageDog: ("../resources/graphics/pocketGraphics/courage dog pocketSource.png"),
  CuteCat: ("../resources/graphics/pocketGraphics/cute cat pocket.png"),
  Dollar: ("../resources/graphics/pocketGraphics/Dollar pocketSource.png"),
  FallingCat: ("../resources/graphics/pocketGraphics/falling cat pocketSource.png"),
  Fish: ("../resources/graphics/pocketGraphics/fish pocketSource.png"),
  Ghost: ("../resources/graphics/pocketGraphics/Ghost pocket.png"),
  GoldenCoins: ("../resources/graphics/pocketGraphics/Golden coins pocket.png"),
  Heart: ("../resources/graphics/pocketGraphics/Heart pocket.png"),
  Hotdog: ("../resources/graphics/pocketGraphics/Hotdog-pocket.png"),
  Husky: ("../resources/graphics/pocketGraphics/husky pocket.png"),
  Icecreampocket: ("../resources/graphics/pocketGraphics/icecream pocket.png"),
  Knife: ("../resources/graphics/pocketGraphics/knife pocket.png"),
  LoveAtFirstBite: ("../resources/graphics/pocketGraphics/Love at first bite.png"),
  Minion: ("../resources/graphics/pocketGraphics/minion pocketSource.png"),
  MonkeyButt: ("../resources/graphics/pocketGraphics/monkey butt pocketSource.png"),
  Octopus: ("../resources/graphics/pocketGraphics/Octopus pocket.png"),
  Palm: ("../resources/graphics/pocketGraphics/palm pocketSource.png"),
  Panda: ("../resources/graphics/pocketGraphics/Panda pocketSource.png"),
  PinupGirl: ("../resources/graphics/pocketGraphics/Pin up girl pocket.png"),
  PinkPanther: ("../resources/graphics/pocketGraphics/pink panter pocketSource.png"),
  Popcorn: ("../resources/graphics/pocketGraphics/Popcorn pocket.png"),
  Pug: ("../resources/graphics/pocketGraphics/pug pocketSource.png"),
  SeaStar: ("../resources/graphics/pocketGraphics/Seastarspocket.png"),
  Sun: ("../resources/graphics/pocketGraphics/Sun umbrella pocket.png"),
  Swimming: ("../resources/graphics/pocketGraphics/Swimming pocketSource.png"),
  TropicalFruit: ("../resources/graphics/pocketGraphics/Tropical fruits pocket.png"),
  WateringFlowers: ("../resources/graphics/pocketGraphics/Watering flowers.png"),
  ZombieHands: ("../resources/graphics/pocketGraphics/Zombie hands pocket.png"),

  // popArtGraphics ---------------------------------------------

  AlbertKisstein: ("../resources/graphics/PopArtGraphics/ALBERT KISSTEIN low.png"),
  AmericanPsycho2: ("../resources/graphics/PopArtGraphics/AMERICAN PSYCHO 2 low.png"),
  AmericanPsycho: ("../resources/graphics/PopArtGraphics/AMERICAN PSYCHO low.png"),
  BenjaminDranklin: ("../resources/graphics/PopArtGraphics/Benjamin Dranklin low.png"),
  CharimanMeow: ("../resources/graphics/PopArtGraphics/CHAIRMAN MEOW low.png"),
  Chef: ("../resources/graphics/PopArtGraphics/CHEF low.png"),
  Covfefe: ("../resources/graphics/PopArtGraphics/COVFEFE.png"),
  Dope: ("../resources/graphics/PopArtGraphics/DOPE.png"),
  Dream: ("../resources/graphics/PopArtGraphics/DREAM low.png"),
  GotMLK: ("../resources/graphics/PopArtGraphics/GOT MLK low.png"),
  Heilstein: ("../resources/graphics/PopArtGraphics/HEILSTEIN low.png"),
  HoHoHoChiMinh: ("../resources/graphics/PopArtGraphics/ho ho ho chi minh.png"),
  ICantBreathe: ("../resources/graphics/PopArtGraphics/I CANT BREATHE.png"),
  JusticeForGeorgeFloyd: ("../resources/graphics/PopArtGraphics/justice for george floyd low.png"),
  LincolnUnknown: ("../resources/graphics/PopArtGraphics/lincoln unknown low.png"),
  MakeAmericaGreyAgain: ("../resources/graphics/PopArtGraphics/MAKE AMERICA GREY AGAIN.png"),
  MeowTseTung: ("../resources/graphics/PopArtGraphics/Meow Tse Tung.png"),
  Merica: ("../resources/graphics/PopArtGraphics/MERICA low.png"),
  MericaTrump: ("../resources/graphics/PopArtGraphics/MERICA TRUMP low.png"),
  NoRacism: ("../resources/graphics/PopArtGraphics/NO RACISM.png"),
  Putintin: ("../resources/graphics/PopArtGraphics/PUTINTIN.png"),
  RocketBoy: ("../resources/graphics/PopArtGraphics/ROCKETBOY low.png"),
  RocketMan: ("../resources/graphics/PopArtGraphics/ROCKETMAN low.png"),
  StraigtOuttaPyongYang: ("../resources/graphics/PopArtGraphics/STRAIGHT OUTTA PYONGYANG.png"),
  SylvesterStalin: ("../resources/graphics/PopArtGraphics/SYLVESTER STALIN.png"),
  TheFuhrer: ("../resources/graphics/PopArtGraphics/THE FUHRER.png"),
  Trump: ("../resources/graphics/PopArtGraphics/TRUMP low.png"),
  UnderControl: ("../resources/graphics/PopArtGraphics/UNDER CONTROL.png"),
  VivaLaEvolucion: ("../resources/graphics/PopArtGraphics/viva la evolucion low.png"),
  WeCanDoIt: ("../resources/graphics/PopArtGraphics/WE CAN DO IT.png"),

  // presidentGraphics ---------------------------------------------

  Franklin: ("../resources/graphics/presidentGraphics/franklin.png"),
  Grant: ("../resources/graphics/presidentGraphics/grant.png"),
  Hamilton: ("../resources/graphics/presidentGraphics/hamilton.png"),
  Jackson: ("../resources/graphics/presidentGraphics/jackson.png"),
  Jefferson: ("../resources/graphics/presidentGraphics/jefferson.png"),
  Lincoln: ("../resources/graphics/presidentGraphics/lincoln.png"),
  Washington: ("../resources/graphics/presidentGraphics/washington.png"),

  // randomGraphics ---------------------------------------------

  AnchorBones: ("../resources/graphics/randomGraphics/Anchor Bones-02.png"),
  Anchor: ("../resources/graphics/randomGraphics/Anchor.png"),
  Astrocode: ("../resources/graphics/randomGraphics/Astrocode.png"),
  Awesome: ("../resources/graphics/randomGraphics/Awesome.png"),
  BananaSkateboard: ("../resources/graphics/randomGraphics/Banana Skateboard.png"),
  BaseballPlayer: ("../resources/graphics/randomGraphics/Baseball Player.png"),
  BasketballPlayer: ("../resources/graphics/randomGraphics/Basketball Player.png"),
  Beetle: ("../resources/graphics/randomGraphics/Beetle.png"),
  BicycleSkull: ("../resources/graphics/randomGraphics/Bicycle Skull.png"),
  BirdsBeard: ("../resources/graphics/randomGraphics/Birds Beard.png"),
  BrainGloves: ("../resources/graphics/randomGraphics/Brain Gloves.png"),
  BreakingNoise: ("../resources/graphics/randomGraphics/Breaking Noise.png"),
  Burger: ("../resources/graphics/randomGraphics/Burger.png"),
  Chainsaw: ("../resources/graphics/randomGraphics/Chainsaw.png"),
  CheSmiley: ("../resources/graphics/randomGraphics/Che Smiley.png"),
  CoffeeTree: ("../resources/graphics/randomGraphics/Coffee Tree.png"),
  Coffee: ("../resources/graphics/randomGraphics/Coffee.png"),
  Crab: ("../resources/graphics/randomGraphics/Crab.png"),
  CrystalLake: ("../resources/graphics/randomGraphics/Crystal Lake.png"),
  DeadSchool: ("../resources/graphics/randomGraphics/Dead  School.png"),
  DeadSea: ("../resources/graphics/randomGraphics/Dead Sea.png"),
  DeathCity: ("../resources/graphics/randomGraphics/Death City.png"),
  Deer2: ("../resources/graphics/randomGraphics/Deer 2.png"),
  Deer3: ("../resources/graphics/randomGraphics/Deer 3.png"),
  DeerButterfly: ("../resources/graphics/randomGraphics/Deer Butterfly.png"),
  Deer: ("../resources/graphics/randomGraphics/Deer.png"),
  DonutBarbell: ("../resources/graphics/randomGraphics/Donut Barbell.png"),
  Eagle: ("../resources/graphics/randomGraphics/Eagle.png"),
  ElectricAnchor: ("../resources/graphics/randomGraphics/Electric Anchor.png"),
  ElectricBalance: ("../resources/graphics/randomGraphics/Electric Balance.png"),
  ElectricBrain: ("../resources/graphics/randomGraphics/Electric Brain.png"),
  ElectricDeer: ("../resources/graphics/randomGraphics/Electric Deer.png"),
  ElectricSkull: ("../resources/graphics/randomGraphics/Electric Skull.png"),
  ElectricSmiley: ("../resources/graphics/randomGraphics/Electric Smiley.png"),
  ElectricalOwl: ("../resources/graphics/randomGraphics/Electrical Owl.png"),
  EnjoyYourLie: ("../resources/graphics/randomGraphics/Enjoy Your Lie.png"),
  FloatLikeButterflyStingLikeBee: ("../resources/graphics/randomGraphics/Float Like Butterfly Sting Like Bee.png"),
  FlourishVandalism: ("../resources/graphics/randomGraphics/Flourish Vandalism.png"),
  FlyingAstronaut: ("../resources/graphics/randomGraphics/Flying Astronaut.png"),
  FroggyNight: ("../resources/graphics/randomGraphics/Froggy Night.png"),
  GhostFaceBats: ("../resources/graphics/randomGraphics/Ghost Face Bats.png"),
  Godzilla: ("../resources/graphics/randomGraphics/Godzilla.png"),
  GoodIdea: ("../resources/graphics/randomGraphics/Good Idea.png"),
  GramophoneDonut: ("../resources/graphics/randomGraphics/Gramophone Donut.png"),
  GreenMonster: ("../resources/graphics/randomGraphics/Green Monster.png"),
  GrenadeMan: ("../resources/graphics/randomGraphics/Grenade.png"),
  HandOfRevolution: ("../resources/graphics/randomGraphics/Hand Of Revolution.png"),
  HandOfZombies: ("../resources/graphics/randomGraphics/Hand Of Zombies.png"),
  HeadphoneDonut: ("../resources/graphics/randomGraphics/Headphone Donut.png"),
  Hipster: ("../resources/graphics/randomGraphics/HIPSTER.png"),
  HomeHeart: ("../resources/graphics/randomGraphics/Home Heart.png"),
  Icecream: ("../resources/graphics/randomGraphics/Ice Cream.png"),
  JasonMoon: ("../resources/graphics/randomGraphics/Jason Moon.png"),
  Kaiju2: ("../resources/graphics/randomGraphics/Kaiju 2.png"),
  Kaiju: ("../resources/graphics/randomGraphics/Kaiju.png"),
  KnowYourRoots: ("../resources/graphics/randomGraphics/Know Your Roots.png"),
  Liberty: ("../resources/graphics/randomGraphics/Liberty.png"),
  LifeAndDeath: ("../resources/graphics/randomGraphics/Life And Death.png"),
  LOL: ("../resources/graphics/randomGraphics/LOL.png"),
  Milkyway: ("../resources/graphics/randomGraphics/Milky Way.png"),
  NatureOfCrime: ("../resources/graphics/randomGraphics/Nature of Crime.png"),
  Nerd: ("../resources/graphics/randomGraphics/NERD.png"),
  Peace: ("../resources/graphics/randomGraphics/Peace.png"),
  PizzaMoon: ("../resources/graphics/randomGraphics/Pizza Moon.png"),
  PizzaScratch: ("../resources/graphics/randomGraphics/Pizza Scratch.png"),
  PizzaUFO: ("../resources/graphics/randomGraphics/Pizza UFO.png"),
  Pizza: ("../resources/graphics/randomGraphics/Pizza.png"),
  Prismzza: ("../resources/graphics/randomGraphics/Prismzza.png"),
  ReaperScream: ("../resources/graphics/randomGraphics/Reaper Scream.png"),
  Recycling: ("../resources/graphics/randomGraphics/Recycling.png"),
  RhymeInPeace: ("../resources/graphics/randomGraphics/Rhyme In Peace.png"),
  RibcageBird: ("../resources/graphics/randomGraphics/Ribcage Bird.png"),
  Scooter: ("../resources/graphics/randomGraphics/Scooter.png"),
  SeaHorse: ("../resources/graphics/randomGraphics/Sea Horse.png"),
  SherlockHolmes: ("../resources/graphics/randomGraphics/Sherlock Holmes.png"),
  Skater: ("../resources/graphics/randomGraphics/Skater.png"),
  SkaterHook: ("../resources/graphics/randomGraphics/Skaterhook.png"),
  SkullNature: ("../resources/graphics/randomGraphics/Skull Nature.png"),
  SmileyMoon: ("../resources/graphics/randomGraphics/Smiley Moon.png"),
  Smiley: ("../resources/graphics/randomGraphics/Smiley.png"),
  SmokingKills: ("../resources/graphics/randomGraphics/Smoking Kills.png"),
  SoundCollector: ("../resources/graphics/randomGraphics/Sound Collector.png"),
  SoundOfRain: ("../resources/graphics/randomGraphics/Sound Of Rain.png"),
  StandAndBleed: ("../resources/graphics/randomGraphics/Stand And Bleed.png"),
  TheBridge: ("../resources/graphics/randomGraphics/The Bridge.png"),
  TheChronicle: ("../resources/graphics/randomGraphics/The Chronicle.png"),
  TheCrow: ("../resources/graphics/randomGraphics/The Crow.png"),
  TheMask: ("../resources/graphics/randomGraphics/The Mask.png"),
  Thunderbolt: ("../resources/graphics/randomGraphics/Thunderbolt.png"),
  TrainSong: ("../resources/graphics/randomGraphics/Train Song.png"),
  truthHurts: ("../resources/graphics/randomGraphics/Truth Hurts.png"),
  UFOInvasion: ("../resources/graphics/randomGraphics/UFO Invasion.png"),
  WarPeace: ("../resources/graphics/randomGraphics/War Peace.png"),
  WeaponFlag: ("../resources/graphics/randomGraphics/Weapon Flag.png"),
  WildBison: ("../resources/graphics/randomGraphics/Wild Bison.png"),
  WildLife: ("../resources/graphics/randomGraphics/Wild Life.png"),
  YinYangCats: ("../resources/graphics/randomGraphics/YinYang Cats.png"),
  ZebraBones: ("../resources/graphics/randomGraphics/Zebra Bones.png"),

  //BlackHistoryGraphics ---------------------------------------------

  // BHM365Days: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONT 365 DAYS.png",
  BHM365Days: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONT 365 DAYS.png",
  BHMMalcolmX: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MALCOLM X.png",
  BHMMap: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MAP.png",
  BHMMLK: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MLK.png",
  BHMPowerHand: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH POWER HAND.png",
  BHM: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH.png",
  BH: "../resources/graphics/BlackHistoryGraphics/BLACK HISTORY.png",
  BLMHand: "../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER HAND.png",
  MartinLutherJunior: "../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER Martin Luther Junior.png",
  BLMMLK: "../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER MLK.png",
  BlackLivesMatter: "../resources/graphics/BlackHistoryGraphics/BLACKLIVESMATTER.png",
  DreamBH: "../resources/graphics/BlackHistoryGraphics/DREAM.png",
  EnoughIsEnough: "../resources/graphics/BlackHistoryGraphics/ENOUGH IS ENOUGH.png",
  FightForChange: "../resources/graphics/BlackHistoryGraphics/FIGHT FOR CHANGE.png",
  FrederickDouglass: "../resources/graphics/BlackHistoryGraphics/FREDERICK DOUGLASS.png",
  FreedomBH: "../resources/graphics/BlackHistoryGraphics/FREEDOM.png",
  JohnLewis: "../resources/graphics/BlackHistoryGraphics/JOHN LEWIS.png",
  EveryMonthBH: "../resources/graphics/BlackHistoryGraphics/MAKE EVERY MONTH BLACK HISTORY MONTH.png",
  MalcolmXBH: "../resources/graphics/BlackHistoryGraphics/MALCOLM X BLACK HISTORY.png",
  MLKBH: "../resources/graphics/BlackHistoryGraphics/MARTIN LUTHER KING BLACK HISTORY.png",
  Riot: "../resources/graphics/BlackHistoryGraphics/RIOT.png",
  WeCanDoAll: "../resources/graphics/BlackHistoryGraphics/WE CAN DO IT.png",

  //CartoonGraphics ---------------------------------------------

  Cat1: ("../resources/graphics/CartoonGraphics/Cat 1.png"),
  Cat2: ("../resources/graphics/CartoonGraphics/Cat 2.png"),
  Cat3: ("../resources/graphics/CartoonGraphics/Cat 3.png"),
  Cat4: ("../resources/graphics/CartoonGraphics/Cat 4.png"),
  Cat5: ("../resources/graphics/CartoonGraphics/Cat 5.png"),
  Cat6: ("../resources/graphics/CartoonGraphics/Cat 6.png"),
  Cat7: ("../resources/graphics/CartoonGraphics/Cat 7.png"),
  Cat8: ("../resources/graphics/CartoonGraphics/Cat 8.png"),
  Cat9: ("../resources/graphics/CartoonGraphics/Cat 9.png"),
  Cat10: ("../resources/graphics/CartoonGraphics/Cat 10.png"),
  Cat11: ("../resources/graphics/CartoonGraphics/Cat 11.png"),
  Cat12: ("../resources/graphics/CartoonGraphics/Cat 12.png"),
  Cat13: ("../resources/graphics/CartoonGraphics/Cat 13.png"),
  Cat14: ("../resources/graphics/CartoonGraphics/Cat 14.png"),
  Cat15: ("../resources/graphics/CartoonGraphics/Cat 15.png"),
  Cat16: ("../resources/graphics/CartoonGraphics/Cat 16.png"),
  Cat17: ("../resources/graphics/CartoonGraphics/Cat 17.png"),
  Cat18: ("../resources/graphics/CartoonGraphics/Cat 18.png"),
  Cat19: ("../resources/graphics/CartoonGraphics/Cat 19.png"),
  Cat20: ("../resources/graphics/CartoonGraphics/Cat 20.png"),
  Cat21: ("../resources/graphics/CartoonGraphics/Cat 21.png"),
  Cat22: ("../resources/graphics/CartoonGraphics/Cat 22.png"),
  Cat23: ("../resources/graphics/CartoonGraphics/Cat 23.png"),
  Cat24: ("../resources/graphics/CartoonGraphics/Cat 24.png"),
  Cat25: ("../resources/graphics/CartoonGraphics/Cat 25.png"),
  Dog1: ("../resources/graphics/CartoonGraphics/Dog 1.png"),
  Dog2: ("../resources/graphics/CartoonGraphics/Dog 2.png"),
  Dog3: ("../resources/graphics/CartoonGraphics/Dog 3.png"),
  Dog4: ("../resources/graphics/CartoonGraphics/Dog 4.png"),
  Dog5: ("../resources/graphics/CartoonGraphics/Dog 5.png"),
  Dog6: ("../resources/graphics/CartoonGraphics/Dog 6.png"),
  Dog7: ("../resources/graphics/CartoonGraphics/Dog 7.png"),
  Dog8: ("../resources/graphics/CartoonGraphics/Dog 8.png"),
  Dog9: ("../resources/graphics/CartoonGraphics/Dog 9.png"),
  Dog10: ("../resources/graphics/CartoonGraphics/Dog 10.png"),
  Dog11: ("../resources/graphics/CartoonGraphics/Dog 11.png"),
  Dog12: ("../resources/graphics/CartoonGraphics/Dog 12.png"),
  Dog13: ("../resources/graphics/CartoonGraphics/Dog 13.png"),
  Dog14: ("../resources/graphics/CartoonGraphics/Dog 14.png"),
  Dog15: ("../resources/graphics/CartoonGraphics/Dog 15.png"),
  Dog16: ("../resources/graphics/CartoonGraphics/Dog 16.png"),
  Dog17: ("../resources/graphics/CartoonGraphics/Dog 17.png"),
  Dog18: ("../resources/graphics/CartoonGraphics/Dog 18.png"),
  Dog19: ("../resources/graphics/CartoonGraphics/Dog 19.png"),
  Dog20: ("../resources/graphics/CartoonGraphics/Dog 20.png"),
  Dog21: ("../resources/graphics/CartoonGraphics/Dog 21.png"),
  Dog22: ("../resources/graphics/CartoonGraphics/Dog 22.png"),
  Dog23: ("../resources/graphics/CartoonGraphics/Dog 23.png"),
  Dog24: ("../resources/graphics/CartoonGraphics/Dog 24.png"),
  Dog25: ("../resources/graphics/CartoonGraphics/Dog 25.png"),
  Dragon1: ("../resources/graphics/CartoonGraphics/Dragon 1.png"),
  Dragon2: ("../resources/graphics/CartoonGraphics/Dragon 2.png"),
  Dragon3: ("../resources/graphics/CartoonGraphics/Dragon 3.png"),
  Dragon4: ("../resources/graphics/CartoonGraphics/Dragon 4.png"),
  Dragon5: ("../resources/graphics/CartoonGraphics/Dragon 5.png"),
  Dragon6: ("../resources/graphics/CartoonGraphics/Dragon 6.png"),
  Dragon7: ("../resources/graphics/CartoonGraphics/Dragon 7.png"),
  Dragon8: ("../resources/graphics/CartoonGraphics/Dragon 8.png"),
  Dragon9: ("../resources/graphics/CartoonGraphics/Dragon 9.png"),
  Dragon10: ("../resources/graphics/CartoonGraphics/Dragon 10.png"),
  Dragon11: ("../resources/graphics/CartoonGraphics/Dragon 11.png"),
  Dragon12: ("../resources/graphics/CartoonGraphics/Dragon 12.png"),
  Dragon13: ("../resources/graphics/CartoonGraphics/Dragon 13.png"),
  Dragon14: ("../resources/graphics/CartoonGraphics/Dragon 14.png"),
  Dragon15: ("../resources/graphics/CartoonGraphics/Dragon 15.png"),
  Dragon16: ("../resources/graphics/CartoonGraphics/Dragon 16.png"),
  Dragon17: ("../resources/graphics/CartoonGraphics/Dragon 17.png"),
  Dragon18: ("../resources/graphics/CartoonGraphics/Dragon 18.png"),
  Dragon19: ("../resources/graphics/CartoonGraphics/Dragon 19.png"),
  Dragon20: ("../resources/graphics/CartoonGraphics/Dragon 20.png"),
  Dragon21: ("../resources/graphics/CartoonGraphics/Dragon 21.png"),
  Dragon22: ("../resources/graphics/CartoonGraphics/Dragon 22.png"),
  Dragon23: ("../resources/graphics/CartoonGraphics/Dragon 23.png"),
  Dragon24: ("../resources/graphics/CartoonGraphics/Dragon 24.png"),
  Dragon25: ("../resources/graphics/CartoonGraphics/Dragon 25.png"),
  Monster: ("../resources/graphics/CartoonGraphics/Monster.png"),
  Monster1: ("../resources/graphics/CartoonGraphics/Monster1.png"),
  Monster2: ("../resources/graphics/CartoonGraphics/Monster2.png"),
  Monster3: ("../resources/graphics/CartoonGraphics/Monster3.png"),
  Monster4: ("../resources/graphics/CartoonGraphics/Monster4.png"),
  Monster5: ("../resources/graphics/CartoonGraphics/Monster5.png"),
  Monster6: ("../resources/graphics/CartoonGraphics/Monster6.png"),
  Monster7: ("../resources/graphics/CartoonGraphics/Monster7.png"),
  Monster8: ("../resources/graphics/CartoonGraphics/Monster8.png"),
  Monster9: ("../resources/graphics/CartoonGraphics/Monster9.png"),
  Monster10: ("../resources/graphics/CartoonGraphics/Monster10.png"),
  Monster11: ("../resources/graphics/CartoonGraphics/Monster11.png"),
  Monster12: ("../resources/graphics/CartoonGraphics/Monster12.png"),
  Monster13: ("../resources/graphics/CartoonGraphics/Monster13.png"),
  Monster14: ("../resources/graphics/CartoonGraphics/Monster14.png"),
  Monster15: ("../resources/graphics/CartoonGraphics/Monster15.png"),
  Monster16: ("../resources/graphics/CartoonGraphics/Monster16.png"),
  Monster17: ("../resources/graphics/CartoonGraphics/Monster17.png"),
  Monster18: ("../resources/graphics/CartoonGraphics/Monster18.png"),
  Monster19: ("../resources/graphics/CartoonGraphics/Monster19.png"),
  Monster20: ("../resources/graphics/CartoonGraphics/Monster20.png"),
  Monster21: ("../resources/graphics/CartoonGraphics/Monster21.png"),
  Monster22: ("../resources/graphics/CartoonGraphics/Monster22.png"),
  Monster23: ("../resources/graphics/CartoonGraphics/Monster23.png"),
  Monster24: ("../resources/graphics/CartoonGraphics/Monster24.png"),
  Monster25: ("../resources/graphics/CartoonGraphics/Monster25.png"),
  Monster26: ("../resources/graphics/CartoonGraphics/Monster26.png"),
  Monster27: ("../resources/graphics/CartoonGraphics/Monster27.png"),
  Monster28: ("../resources/graphics/CartoonGraphics/Monster28.png"),
  Monster29: ("../resources/graphics/CartoonGraphics/Monster29.png"),
  Monster30: ("../resources/graphics/CartoonGraphics/Monster30.png"),
  Monster31: ("../resources/graphics/CartoonGraphics/Monster31.png"),
  Monster32: ("../resources/graphics/CartoonGraphics/Monster32.png"),
  Monster33: ("../resources/graphics/CartoonGraphics/Monster33.png"),
  Monster34: ("../resources/graphics/CartoonGraphics/Monster34.png"),
  Monster35: ("../resources/graphics/CartoonGraphics/Monster35.png"),
  Monster36: ("../resources/graphics/CartoonGraphics/Monster36.png"),
  Monster37: ("../resources/graphics/CartoonGraphics/Monster37.png"),
  Monster38: ("../resources/graphics/CartoonGraphics/Monster38.png"),
  Monster39: ("../resources/graphics/CartoonGraphics/Monster39.png"),
  Monster40: ("../resources/graphics/CartoonGraphics/Monster40.png"),
  Monster41: ("../resources/graphics/CartoonGraphics/Monster41.png"),
  Monster42: ("../resources/graphics/CartoonGraphics/Monster42.png"),
  Monster43: ("../resources/graphics/CartoonGraphics/Monster43.png"),
  Monster44: ("../resources/graphics/CartoonGraphics/Monster44.png"),
  Monster45: ("../resources/graphics/CartoonGraphics/Monster45.png"),
  Monster46: ("../resources/graphics/CartoonGraphics/Monster46.png"),
  Monster47: ("../resources/graphics/CartoonGraphics/Monster47.png"),
  Monster48: ("../resources/graphics/CartoonGraphics/Monster48.png"),
  Monster49: ("../resources/graphics/CartoonGraphics/Monster49.png"),
  Monster50: ("../resources/graphics/CartoonGraphics/Monster50.png"),
  Snake1: ("../resources/graphics/CartoonGraphics/Snake 1.png"),
  Snake2: ("../resources/graphics/CartoonGraphics/Snake 2.png"),
  Snake3: ("../resources/graphics/CartoonGraphics/Snake 3.png"),
  Snake4: ("../resources/graphics/CartoonGraphics/Snake 4.png"),
  Snake5: ("../resources/graphics/CartoonGraphics/Snake 5.png"),
  Snake6: ("../resources/graphics/CartoonGraphics/Snake 6.png"),
  Snake7: ("../resources/graphics/CartoonGraphics/Snake 7.png"),
  Snake8: ("../resources/graphics/CartoonGraphics/Snake 8.png"),
  Snake9: ("../resources/graphics/CartoonGraphics/Snake 9.png"),
  Snake10: ("../resources/graphics/CartoonGraphics/Snake 10.png"),
  Snake11: ("../resources/graphics/CartoonGraphics/Snake 11.png"),
  Snake12: ("../resources/graphics/CartoonGraphics/Snake 12.png"),
  Snake13: ("../resources/graphics/CartoonGraphics/Snake 13.png"),
  Snake14: ("../resources/graphics/CartoonGraphics/Snake 14.png"),
  Snake15: ("../resources/graphics/CartoonGraphics/Snake 15.png"),
  Snake16: ("../resources/graphics/CartoonGraphics/Snake 16.png"),
  Snake17: ("../resources/graphics/CartoonGraphics/Snake 17.png"),
  Snake18: ("../resources/graphics/CartoonGraphics/Snake 18.png"),
  Snake19: ("../resources/graphics/CartoonGraphics/Snake 19.png"),
  Snake20: ("../resources/graphics/CartoonGraphics/Snake 20.png"),
  Snake21: ("../resources/graphics/CartoonGraphics/Snake 21.png"),
  Snake22: ("../resources/graphics/CartoonGraphics/Snake 22.png"),
  Snake23: ("../resources/graphics/CartoonGraphics/Snake 23.png"),
  Snake24: ("../resources/graphics/CartoonGraphics/Snake 24.png"),
  Snake25: ("../resources/graphics/CartoonGraphics/Snake 25.png"),

  // Super Hero Graphics ---------------------------------------------

  ANTIVENOMPOP: ("../resources/graphics/SuperHeroGraphics/ANTI VENOM POP.png"),
  ANTMANENDGAME: ("../resources/graphics/SuperHeroGraphics/ANTMAN ENDGAME.png"),
  ARYASTARK: ("../resources/graphics/SuperHeroGraphics/ARYA STARK.png"),
  BACKTOTHEFUTURE: ("../resources/graphics/SuperHeroGraphics/BACK TO THE FUTURE.png"),
  Battleforeternia: ("../resources/graphics/SuperHeroGraphics/Battle for eternia.png"),
  BATMANYROBIN: ("../resources/graphics/SuperHeroGraphics/BATMAN Y ROBIN.png"),
  BezitaVader: ("../resources/graphics/SuperHeroGraphics/Bezita Vader.png"),
  blackpanter01: ("../resources/graphics/SuperHeroGraphics/black panter 01.png"),
  BlackTrooper: ("../resources/graphics/SuperHeroGraphics/Black Trooper.png"),
  BLACKWIDOWENDGAME: ("../resources/graphics/SuperHeroGraphics/BLACK WIDOW ENDGAME.png"),
  BLACKW: ("../resources/graphics/SuperHeroGraphics/BLACKW.png"),
  BRITNEY: ("../resources/graphics/SuperHeroGraphics/BRITNEY.png"),
  CAPITANAMERICA2: ("../resources/graphics/SuperHeroGraphics/CAPITAN AMERICA 2.png"),
  CAPITANAMERICA3: ("../resources/graphics/SuperHeroGraphics/CAPITAN AMERICA 3.png"),
  CAPITANAMARVEL: ("../resources/graphics/SuperHeroGraphics/CAPITANA MARVEL.png"),
  CAPTAINAMERICA1STAVENGER: ("../resources/graphics/SuperHeroGraphics/CAPTAIN AMERICA 1ST AVENGER.png"),
  CAPTAINENDGAMEV2: ("../resources/graphics/SuperHeroGraphics/CAPTAIN ENDGAME V2.png"),
  CAPTAINENDGAME: ("../resources/graphics/SuperHeroGraphics/CAPTAIN ENDGAME.png"),
  CAPTAIN1: ("../resources/graphics/SuperHeroGraphics/CAPTAIN1.png"),
  CasadepapelDalírun: ("../resources/graphics/SuperHeroGraphics/Casa de papel Dalí run.png"),
  CasadepapelgrupoCartoon: ("../resources/graphics/SuperHeroGraphics/Casa de papel grupo Cartoon.png"),
  casadepapel: ("../resources/graphics/SuperHeroGraphics/casa de papel.png"),
  CHEWBACCA: ("../resources/graphics/SuperHeroGraphics/CHEWBACCA.png"),
  chubaca: ("../resources/graphics/SuperHeroGraphics/chubaca.png"),
  DAENERYS1: ("../resources/graphics/SuperHeroGraphics/DAENERYS 1.png"),
  DAERAVILFUNKOVECTOR: ("../resources/graphics/SuperHeroGraphics/DAERAVIL FUNKO VECTOR.png"),
  deadtina: ("../resources/graphics/SuperHeroGraphics/dead tina.png"),
  deadpool01: ("../resources/graphics/SuperHeroGraphics/deadpool 01.png"),
  DeadpoolMercenary: ("../resources/graphics/SuperHeroGraphics/Deadpool Mercenary.png"),
  DeadpoolTacos: ("../resources/graphics/SuperHeroGraphics/Deadpool Tacos.png"),
  DEADPOOL: ("../resources/graphics/SuperHeroGraphics/DEADPOOL.png"),
  Droids: ("../resources/graphics/SuperHeroGraphics/Droids.png"),
  Dumbo2: ("../resources/graphics/SuperHeroGraphics/Dumbo 2.png"),
  FLINTSTONES: ("../resources/graphics/SuperHeroGraphics/FLINTSTONES.png"),
  FLYINGDRAGON: ("../resources/graphics/SuperHeroGraphics/FLYINGDRAGON.png"),
  FORTNITE: ("../resources/graphics/SuperHeroGraphics/FORTNITE.png"),
  FreddyvsJason: ("../resources/graphics/SuperHeroGraphics/Freddy vs Jason.png"),
  Freddy: ("../resources/graphics/SuperHeroGraphics/Freddy.png"),
  FUNKOIT: ("../resources/graphics/SuperHeroGraphics/FUNKO IT.png"),
  funkovegeta: ("../resources/graphics/SuperHeroGraphics/funko vegeta.png"),
  GHOSTBUSTERS4: ("../resources/graphics/SuperHeroGraphics/GHOSTBUSTERS 4.png"),
  GHOSTBUSTERS: ("../resources/graphics/SuperHeroGraphics/GHOSTBUSTERS.png"),
  GROOT2: ("../resources/graphics/SuperHeroGraphics/GROOT 2.png"),
  GROOT: ("../resources/graphics/SuperHeroGraphics/GROOT.png"),
  HarleyQueen: ("../resources/graphics/SuperHeroGraphics/HarleyQueen.png"),
  HarleyQueenB: ("../resources/graphics/SuperHeroGraphics/HarleyQueenB.png"),
  HARRYPOTTER2: ("../resources/graphics/SuperHeroGraphics/HARRY POTTER 2.png"),
  HARRYPOTTER1: ("../resources/graphics/SuperHeroGraphics/HARRY POTTER1.png"),
  HEISENBERG: ("../resources/graphics/SuperHeroGraphics/HEISENBERG.png"),
  HERMIONE: ("../resources/graphics/SuperHeroGraphics/HERMIONE.png"),
  ENDGAMEV2: ("../resources/graphics/SuperHeroGraphics/HULK ENDGAME V2.png"),
  ENDGAME: ("../resources/graphics/SuperHeroGraphics/HULK ENDGAME.png"),
  HULK: ("../resources/graphics/SuperHeroGraphics/HULK.png"),
  IRONSPIDER: ("../resources/graphics/SuperHeroGraphics/IRON SPIDER.png"),
  IRONMANENDGAME: ("../resources/graphics/SuperHeroGraphics/IRONMAN ENDGAME.png"),
  It: ("../resources/graphics/SuperHeroGraphics/It.png"),
  JIMIHENDRIX: ("../resources/graphics/SuperHeroGraphics/JIMI HENDRIX.png"),
  JOKER: ("../resources/graphics/SuperHeroGraphics/JOKER.png"),
  JURASICPOP: ("../resources/graphics/SuperHeroGraphics/JURASIC POP.png"),
  JURASIC2: ("../resources/graphics/SuperHeroGraphics/JURASSIC2.png"),
  kissfunko: ("../resources/graphics/SuperHeroGraphics/kiss funko.png"),
  LOKISARMY: ("../resources/graphics/SuperHeroGraphics/LOKIS ARMY.png"),
  MARTYSKATEBOARD: ("../resources/graphics/SuperHeroGraphics/MARTY SKATEBOARD.png"),
  MARTY: ("../resources/graphics/SuperHeroGraphics/MARTY.png"),
  MEGAMANFUNKO: ("../resources/graphics/SuperHeroGraphics/MEGAMAN FUNKO.png"),
  NIGHTKING2: ("../resources/graphics/SuperHeroGraphics/NIGHT KING 2.png"),
  NIGHTKING3: ("../resources/graphics/SuperHeroGraphics/NIGHT KING 3.png"),
  NIGHTKING: ("../resources/graphics/SuperHeroGraphics/NIGHT KING.png"),
  PREDATOR: ("../resources/graphics/SuperHeroGraphics/PREDATOR.png"),
  REBELLIONEMPIRE: ("../resources/graphics/SuperHeroGraphics/REBELLION EMPIRE.png"),
  ROCKSTEADY: ("../resources/graphics/SuperHeroGraphics/ROCKSTEADY.png"),
  RONINENDGAME: ("../resources/graphics/SuperHeroGraphics/RONIN ENDGAME.png"),
  ScartTerry: ("../resources/graphics/SuperHeroGraphics/Scart Terry.png"),
  SIRENITA: ("../resources/graphics/SuperHeroGraphics/SIRENITA.png"),
  SKELETOR2: ("../resources/graphics/SuperHeroGraphics/SKELETOR 2.png"),
  SKELETORCONQUERGRAYSKULL: ("../resources/graphics/SuperHeroGraphics/SKELETOR CONQUER GRAYSKULL.png"),
  SONIC: ("../resources/graphics/SuperHeroGraphics/SONIC.png"),
  SPIDERMAN2: ("../resources/graphics/SuperHeroGraphics/SPIDERMAN 2.png"),
  SPIDERMAN: ("../resources/graphics/SuperHeroGraphics/SPIDERMAN.png"),
  STANLEECOMPL: ("../resources/graphics/SuperHeroGraphics/STAN LEE COMPL.png"),
  STITCH: ("../resources/graphics/SuperHeroGraphics/STITCH.png"),
  STORMTROOPER: ("../resources/graphics/SuperHeroGraphics/STORM TROOPER.png"),
  SUPERMAN: ("../resources/graphics/SuperHeroGraphics/SUPERMAN.png"),
  TARGARYEN: ("../resources/graphics/SuperHeroGraphics/TARGARYEN.png"),
  THANOSENDGAMEV2: ("../resources/graphics/SuperHeroGraphics/THANOS ENDGAME V2.png"),
  THANOSENDGAME: ("../resources/graphics/SuperHeroGraphics/THANOS ENDGAME.png"),
  THANOS: ("../resources/graphics/SuperHeroGraphics/THANOS.png"),
  TheJoker: ("../resources/graphics/SuperHeroGraphics/The Joker.png"),
  THOR4: ("../resources/graphics/SuperHeroGraphics/THOR 4.png"),
  THORENDGAME: ("../resources/graphics/SuperHeroGraphics/THOR ENDGAME.png"),
  thor: ("../resources/graphics/SuperHeroGraphics/thor.png"),
  TMNT2: ("../resources/graphics/SuperHeroGraphics/TMNT 2.png"),
  Turtles: ("../resources/graphics/SuperHeroGraphics/Turtles.png"),
  VADERKENOBI: ("../resources/graphics/SuperHeroGraphics/VADER KENOBI.png"),
  VENOM2: ("../resources/graphics/SuperHeroGraphics/VENOM 2.png"),
  VENOM1: ("../resources/graphics/SuperHeroGraphics/VENOM1.png"),
  WONDERWOMANRETRO: ("../resources/graphics/SuperHeroGraphics/WONDER WOMAN RETRO.png"),
  wonderwomanfunko: ("../resources/graphics/SuperHeroGraphics/wonder woman funko.png"),
};

export default IMG;
